AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Builds serverless API with Lambda functions, API Gateway, SQS Queue,
  and DynamoDB table.

  '
Globals:
  Function:
    Timeout: 3
Resources:
  GetMessagesFunction:
    Type: AWS::Serverless::Function
    Description: Get all IoT messages in DynamoDB table (scan)
    Properties:
      CodeUri: s3://gstafford-sam-demo/c6cf3adafe4d597ff046ca1fc9c996e5
      Handler: app.getMessages
      Runtime: nodejs10.x
      Policies:
      - DynamoDBCrudPolicy:
          TableName: IotDemoTable
      - SSMParameterReadPolicy:
          ParameterName: iot_demo/table_name
      Environment:
        Variables:
          TABLE_NAME:
            Ref: IotDemoTable
      Events:
        getMessages:
          Type: Api
          Properties:
            Path: /message
            Method: get
  GetMessageFunction:
    Type: AWS::Serverless::Function
    Description: Get one IoT message based on timestamp and location
    Properties:
      CodeUri: s3://gstafford-sam-demo/c6cf3adafe4d597ff046ca1fc9c996e5
      Handler: app.getMessage
      Runtime: nodejs10.x
      Policies:
      - DynamoDBCrudPolicy:
          TableName: IotDemoTable
      - SSMParameterReadPolicy:
          ParameterName: iot_demo/table_name
      Environment:
        Variables:
          TABLE_NAME:
            Ref: IotDemoTable
      Events:
        getMessages:
          Type: Api
          Properties:
            Path: /message/{date}
            Method: get
  PostMessageFunction:
    Type: AWS::Serverless::Function
    Description: Create new IoT message item in DynamoDB table
    Properties:
      CodeUri: s3://gstafford-sam-demo/e3c2378b11ffe5a4dbbc3cadb52a7fa1
      Handler: app.postMessage
      Runtime: nodejs10.x
      Policies:
      - DynamoDBCrudPolicy:
          TableName: IotDemoTable
      - SSMParameterReadPolicy:
          ParameterName: iot_demo/table_name
      Environment:
        Variables:
          TABLE_NAME:
            Ref: IotDemoTable
      Events:
        postMessage:
          Type: Api
          Properties:
            Path: /message
            Method: post
  SqsToDynamoDbFunction:
    Type: AWS::Serverless::Function
    Description: Post new IoT message to SQS
    Properties:
      CodeUri: s3://gstafford-sam-demo/fce47b8dae8f8a79fc129d9fb4a006d1
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 256
      Policies:
      - DynamoDBCrudPolicy:
          TableName: IotDemoTable
      Events:
        SqsToDynamoDb:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - IotDemoQueue
              - Arn
            BatchSize: 10
            Enabled: true
  IotDemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IotDemoTable
      AttributeDefinitions:
      - AttributeName: date
        AttributeType: S
      - AttributeName: time
        AttributeType: S
      KeySchema:
      - AttributeName: date
        KeyType: HASH
      - AttributeName: time
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  IotDemoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: IotDemoQueue
Outputs:
  GetMessagesApi:
    Description: API Gateway endpoint URL for Prod stage for GetMessagesFunction
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getMessages/
  GetMessagesFunction:
    Description: GetMessagesFunction Lambda ARN
    Value:
      Fn::GetAtt:
      - GetMessagesFunction
      - Arn
  GetMessagesFunctionIamRole:
    Description: Implicit IAM Role created for GetMessagesFunction
    Value:
      Fn::GetAtt:
      - GetMessagesFunctionRole
      - Arn
  SqsToDynamoDbFunctionApi:
    Description: API Gateway endpoint URL for Prod stage for SqsToDynamoDbFunction
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getMessages/
  SqsToDynamoDbFunction:
    Description: SqsToDynamoDb Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SqsToDynamoDbFunction
      - Arn
  SqsToDynamoDbFunctionIamRole:
    Description: Implicit IAM Role created for SqsToDynamoDb function
    Value:
      Fn::GetAtt:
      - SqsToDynamoDbFunctionRole
      - Arn
