AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'iot_dynamodb

  SAM Template for iot_dynamodb

  '
Globals:
  Function:
    Timeout: 3
Resources:
  GetMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://gstafford-sam-demo/6ee6f5bd27aecf6dc57518a373e781e9
      Handler: app.getMessages
      Runtime: nodejs10.x
      Policies:
      - DynamoDBCrudPolicy:
          TableName: IotDemoTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: IotDemoTable
      Events:
        getMessages:
          Type: Api
          Properties:
            Path: /message
            Method: get
  GetMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://gstafford-sam-demo/6ee6f5bd27aecf6dc57518a373e781e9
      Handler: app.getMessage
      Runtime: nodejs10.x
      Policies:
      - DynamoDBCrudPolicy:
          TableName: IotDemoTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: IotDemoTable
      Events:
        getMessages:
          Type: Api
          Properties:
            Path: /message/{timestamp}
            Method: get
  PostMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://gstafford-sam-demo/e3c2378b11ffe5a4dbbc3cadb52a7fa1
      Handler: app.postMessage
      Runtime: nodejs10.x
      Policies:
      - DynamoDBCrudPolicy:
          TableName: IotDemoTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: IotDemoTable
      Events:
        postMessage:
          Type: Api
          Properties:
            Path: /message
            Method: post
  SqsToDynamoDbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://gstafford-sam-demo/fce47b8dae8f8a79fc129d9fb4a006d1
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - DynamoDBCrudPolicy:
          TableName: IotDemoTable
      Events:
        SqsToDynamoDb:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - IotDemoQueue
              - Arn
            BatchSize: 10
            Enabled: true
  IotDemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IotDemoTable
      AttributeDefinitions:
      - AttributeName: timestamp
        AttributeType: N
      - AttributeName: location
        AttributeType: S
      KeySchema:
      - AttributeName: timestamp
        KeyType: HASH
      - AttributeName: location
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  IotDemoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: IotDemoQueue
Outputs:
  GetMessagesApi:
    Description: API Gateway endpoint URL for Prod stage for GetMessagesFunction
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getMessages/
  GetMessagesFunction:
    Description: GetMessagesFunction Lambda ARN
    Value:
      Ref: GetMessagesFunction
  GetMessagesFunctionIamRole:
    Description: Implicit IAM Role created for GetMessagesFunction
    Value:
      Fn::GetAtt:
      - GetMessagesFunctionRole
      - Arn
  SqsToDynamoDbFunction:
    Description: SqsToDynamoDb Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SqsToDynamoDbFunction
      - Arn
  SqsToDynamoDbFunctionIamRole:
    Description: Implicit IAM Role created for SqsToDynamoDb function
    Value:
      Fn::GetAtt:
      - SqsToDynamoDbFunctionRole
      - Arn
