AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iot_dynamodb

  SAM Template for iot_dynamodb

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetMessagesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: iot_dynamodb_getMessages/
      Handler: app.getMessages
      Runtime: nodejs10.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: IotDemoTable
      Environment:
        Variables:
          TABLE_NAME: !Ref IotDemoTable
      Events:
        getMessages:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message
            Method: get
  GetMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: iot_dynamodb_getMessages/
      Handler: app.getMessage
      Runtime: nodejs10.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: IotDemoTable
      Environment:
        Variables:
          TABLE_NAME: !Ref IotDemoTable
      Events:
        getMessages:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message/{timestamp}
            Method: get
  PostMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: iot_dynamodb_postMessage/
      Handler: app.postMessage
      Runtime: nodejs10.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: IotDemoTable
      Environment:
        Variables:
          TABLE_NAME: !Ref IotDemoTable
      Events:
        postMessage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message
            Method: post
  SqsToDynamoDbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: iot_sqs_to_dynamodb/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: IotDemoTable
      Events:
        SqsToDynamoDb:
          Type: SQS
          Properties:
            Queue: !GetAtt IotDemoQueue.Arn
            BatchSize: 10
            Enabled: true
  IotDemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IotDemoTable
      AttributeDefinitions:
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: location
          AttributeType: S
      KeySchema:
        - AttributeName: timestamp
          KeyType: HASH
        - AttributeName: location
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  IotDemoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: IotDemoQueue

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetMessagesApi:
    Description: "API Gateway endpoint URL for Prod stage for GetMessagesFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getMessages/"
  GetMessagesFunction:
    Description: "GetMessagesFunction Lambda ARN"
    Value: !Ref GetMessagesFunction
  GetMessagesFunctionIamRole:
    Description: "Implicit IAM Role created for GetMessagesFunction"
    Value: !GetAtt GetMessagesFunctionRole.Arn
  SqsToDynamoDbFunction:
    Description: "SqsToDynamoDb Lambda Function ARN"
    Value: !GetAtt SqsToDynamoDbFunction.Arn
  SqsToDynamoDbFunctionIamRole:
    Description: "Implicit IAM Role created for SqsToDynamoDb function"
    Value: !GetAtt SqsToDynamoDbFunctionRole.Arn
